try to work around missing py35 support
from the build log:
[...]
ERROR:   py35-django18: InterpreterNotFound: python3.5
ERROR:   py35-django19: InterpreterNotFound: python3.5
[...]